# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'MarsRoversExplorer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarsRoversExplorer

  pod 'Kingfisher', '~> 5.0'
  pod 'lottie-ios'	

  target 'MarsRoversExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarsRoversExplorerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
